# This file is used by Render to define your infrastructure.
# You can learn more about this file at https://render.com/docs/yaml-spec

databases:
  - name: testify-db
    plan: free
    postgresMajorVersion: 14

services:
  - type: web
    name: testify-api
    runtime: docker # The key is 'runtime', not 'env'
    # buildCommand and startCommand are handled by the Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: testify-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: testify-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: testify-db
          property: password
